<template><div><h3 id="页面ui图" tabindex="-1"><a class="header-anchor" href="#页面ui图"><span>页面ui图</span></a></h3>
<p><img src="@source/static/mishop/1.jpg" alt="">
<img src="@source/static/mishop/2.jpg" alt="">
<img src="@source/static/mishop/3.jpg" alt="">
<img src="@source/static/mishop/4.jpg" alt="">
<img src="@source/static/mishop/5.jpg" alt="">
<img src="@source/static/mishop/6.jpg" alt="">
<img src="@source/static/mishop/7.jpg" alt="">
<img src="@source/static/mishop/8.jpg" alt="">
<img src="@source/static/mishop/9.jpg" alt="">
<img src="@source/static/mishop/10.jpg" alt="">
<img src="@source/static/mishop/11.jpg" alt="">
<img src="@source/static/mishop/12.png" alt="">
<img src="@source/static/mishop/13.png" alt="">
<img src="@source/static/mishop/14.png" alt="">
<img src="@source/static/mishop/15.png" alt="">
<img src="@source/static/mishop/16.png" alt="">
<img src="@source/static/mishop/17.png" alt="">
<img src="@source/static/mishop/18.png" alt="">
<img src="@source/static/mishop/19.png" alt="">
<img src="@source/static/mishop/20.png" alt="">
<img src="@source/static/mishop/21.png" alt="">
<img src="@source/static/mishop/22.png" alt="">
<img src="@source/static/mishop/23.png" alt="">
<img src="@source/static/mishop/24.png" alt="">
<img src="@source/static/mishop/25.png" alt="">
<img src="@source/static/mishop/26.png" alt="">
<img src="@source/static/mishop/27.png" alt="">
<img src="@source/static/mishop/28.png" alt="">
<img src="@source/static/mishop/29.png" alt="">
<img src="@source/static/mishop/30.png" alt="">
<img src="@source/static/mishop/31.png" alt="">
<img src="@source/static/mishop/32.png" alt="">
<img src="@source/static/mishop/33.png" alt="">
<img src="@source/static/mishop/34.png" alt="">
<img src="@source/static/mishop/35.png" alt="">
<img src="@source/static/mishop/36.png" alt="">
<img src="@source/static/mishop/37.png" alt="">
<img src="@source/static/mishop/38.png" alt="">
<img src="@source/static/mishop/39.png" alt="">
<img src="@source/static/mishop/40.png" alt="">
<img src="@source/static/mishop/41.png" alt="">
<img src="@source/static/mishop/42.png" alt="">
<img src="@source/static/mishop/43.png" alt="">
<img src="@source/static/mishop/44.png" alt="">
<img src="@source/static/mishop/45.png" alt="">
<img src="@source/static/mishop/46.png" alt="">
<img src="@source/static/mishop/47.png" alt="">
<img src="@source/static/mishop/48.png" alt="">
<img src="@source/static/mishop/49.png" alt="">
<img src="@source/static/mishop/50.png" alt="">
<img src="@source/static/mishop/51.png" alt="">
<img src="@source/static/mishop/52.png" alt="">
<img src="@source/static/mishop/53.png" alt="">
<img src="@source/static/mishop/54.png" alt="">
<img src="@source/static/mishop/55.png" alt="">
<img src="@source/static/mishop/56.png" alt="">
<img src="@source/static/mishop/57.png" alt="">
<img src="@source/static/mishop/58.png" alt="">
<img src="@source/static/mishop/59.png" alt="">
<img src="@source/static/mishop/60.png" alt="">
<img src="@source/static/mishop/61.png" alt="">
<img src="@source/static/mishop/62.png" alt="">
<img src="@source/static/mishop/63.png" alt="">
<img src="@source/static/mishop/64.png" alt="">
<img src="@source/static/mishop/65.png" alt="">
<img src="@source/static/mishop/66.png" alt="">
<img src="@source/static/mishop/67.png" alt="">
<img src="@source/static/mishop/68.png" alt="">
<img src="@source/static/mishop/69.jpg" alt="">
<img src="@source/static/mishop/70.jpg" alt="">
<img src="@source/static/mishop/71.jpg" alt="">
<img src="@source/static/mishop/72.jpg" alt=""></p>
</div></template>


