packages:
  - packages/*
  - slidev/*
  - vscode/*
  - vue/*
  - myblog

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - core-js-pure
  - cypress
  - ejs
  - es5-ext
  - esbuild
  - less
  - playwright-chromium
  - protobufjs
  - puppeteer
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
  - yorkie
