/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    LcAirportPickup: typeof import('./src/components/lcSingleProduct/lcAirportPickup/index.vue')['default']
    LcCalendar: typeof import('./src/components/lcCalendar/index.vue')['default']
    LcCarProductDetail: typeof import('./src/components/lcSingleProduct/lcCarProductDetail/index.vue')['default']
    LcEmpty: typeof import('./src/components/lcEmpty/index.vue')['default']
    LcNavMore: typeof import('./src/components/lcNavMore/index.vue')['default']
    LcPosition: typeof import('./src/components/lcPosition/index.vue')['default']
    LcPrice: typeof import('./src/components/lcPrice/index.vue')['default']
    LcSearch: typeof import('./src/components/lcSearch/index.vue')['default']
    LcSingleProduct: typeof import('./src/components/lcSingleProduct/index.vue')['default']
    LcSingleProductBooking: typeof import('./src/components/lcSingleProduct/lcSingleProductBooking/index.vue')['default']
    LcSingleProductDetail: typeof import('./src/components/lcSingleProduct/lcSingleProductDetail/index.vue')['default']
    LcSkeleton: typeof import('./src/components/lcSkeleton/index.vue')['default']
    LcTargetPosition: typeof import('./src/components/lcTargetPosition/index.vue')['default']
    NavParent: typeof import('./src/components/navParent/index.vue')['default']
    OptionPop: typeof import('./src/components/optionPop/index.vue')['default']
    PageListFilter: typeof import('./src/components/pageListFilter/index.vue')['default']
    PageListItem: typeof import('./src/components/pageListItem/index.vue')['default']
    PageListProductHandler: typeof import('./src/components/pageListProductHandler/index.vue')['default']
    PageListProductList: typeof import('./src/components/pageListProductList/index.vue')['default']
    Pagination: typeof import('./src/components/pagination/index.vue')['default']
    ShareFooter: typeof import('./src/components/shareFooter/index.vue')['default']
    ShareHeader: typeof import('./src/components/shareHeader/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
