<template><h2 id="小程序" tabindex="-1"><a class="header-anchor" href="#小程序" aria-hidden="true">#</a> 小程序</h2>
<ul>
<li>
<p>支付宝小程序开发技术</p>
</li>
<li>
<p>小程序跨端框架技术</p>
</li>
<li>
<p>将微信小程序迁移到支付宝小程序注意事项：</p>
<ul>
<li>
<p>微信平台与支付宝平台能力的差异：</p>
<ul>
<li>
<p>登录</p>
<ul>
<li>微信：<code>wx.login</code></li>
<li>支付宝：<code>my.getAuthCode</code></li>
</ul>
</li>
<li>
<p>支付</p>
<ul>
<li>微信：<code>wx.requestPayment</code></li>
<li>支付宝：<code>my.tradePay</code></li>
</ul>
</li>
<li>
<p>插件</p>
</li>
<li>
<p>扩展库</p>
</li>
<li>
<p>组件</p>
</li>
</ul>
</li>
<li>
<p>js 语法差异</p>
</li>
</ul>
</li>
</ul>
<h2 id="万象营销专题" tabindex="-1"><a class="header-anchor" href="#万象营销专题" aria-hidden="true">#</a> 万象营销专题</h2>
<ul>
<li>万象组件开发技术</li>
</ul>
</template>
